import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StarknetProvider from "../components/StarknetProvider";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Seamless UI",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StarknetProvider>
          <Header />
          {children}
        </StarknetProvider>
      </body>
    </html>
  );
}
