import type { Metadata } from "next";
import "./globals.css";
import StarknetProvider from "./StarknetProvider";

/// <reference types="react/canary" />

export const metadata: Metadata = {
  title: "SeamlessUI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StarknetProvider>
        <body className={`antialiased`}>{children}</body>
      </StarknetProvider>
    </html>
  );
}
